#+TITLE: Diff-hl replacing git-gutter
#+DATE: [2016-01-31 Sun]
#+KEYWORDS: emacs, git, diff
#+DESCRIPTION: Discovering a replacement for git-gutter
#+OPTIONS: title:nil

#+BEGIN_HTML
<header><h1 class="title"><a href="./diff-hl-replacing-git-gutter.html">Diff-hl replacing git-gutter</a><span> </span><span class="timestamp-wrapper"><span class="timestamp">(January 31, 2016)</span></span></h1><div class="back-to-index"><a href="./">Back to index</a></div></header>
#+END_HTML

I used to have a perfectly working git gutter setup in Vim, but when I switched
to Emacs, I found that the [[https://github.com/syohex/emacs-git-gutter][emacs-git-gutter]] package was quite buggy. Since it
never worked properly for me, I ended up just relying on magit to view what
changes I'd made.

Today, however, I started using the [[https://github.com/dgutov/diff-hl][diff-hl]] package. It unobtrusively colors
the fringe green, red, or blue, and so far has been working with zero problems.

#+BEGIN_SRC elisp
(use-package diff-hl
  :ensure t
  :config
  (progn
    (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh)
    (global-diff-hl-mode)
    (diff-hl-flydiff-mode)))
#+END_SRC

Edit: It seems that this package has problems with magit, and I ended up having
to fully purge it from emacs. Whenever magit runs a =post-command-hook=, it
freezes to the point where I can only solve it by force
quitting. @@html:<kbd>M-x</kbd>@@ stops working when this happens, as well as
@@html:<kbd>C-x C-c</kbd>@@. I might come back to this and try again in the
future.
