#+TITLE: Leopold FC750R Mechanical Keyboard Review
#+DATE: [2017-08-14 Mon]
#+KEYWORDS: leopold fc750r, mechanical keyboards, product review, typing
#+DESCRIPTION: A review of the Leopold FC750R keyboard
#+SETUPFILE: setup.org

{{{post_title(./leopold-fc750r-mechanical-keyboard-review.html, Leopold FC750R Mechanical Keyboard Review, August 14\, 2017)}}}

I've been using the Leopold FC750R (the white PBT, brown Cherry MX model) over
the past 6 months, both in the office and at home. I decided to get the
tenkeyless model instead of the smaller variant, so that the arrow keys would
not be tucked next to the right Control key and other modifiers.

Pros:
- Side-printed keys, letters will never smudge or wear off
- Feels well-built
- Supposedly there's a rubber mat at the bottom of the case, to dampen echo
- Satisfying color; it's an off-white/arctic color

Cons
- Not programmable
- Function keys don't double as media keys (on Linux)
- Port for USB is tucked in a groove underneath instead of directly in the back,
  not good for those who use thick braided cables

The fact that the keyboard doesn't have media keys on Linux would be the biggest
con. However, I was able to work around it by binding prev/pause/next and volume
controls to F10-F12 and Ps/Sr, ScrLk, and Pa/Br. I would have preferred to not
have to, but after fiddling with =xbindkeys= for a while, I got it working
decently enough.

For my next keyboard, I am thinking of buying/building a Planck. It's much
smaller, the keys are arranged in columns instead of staggered, and it's
programmable. I realized I need another keyboard for travel because I recently
traveled to Los Angeles and brought my ThinkPad but not my keyboard. The desk at
the hotel was way too tall, making it uncomfortable to type directly on the
laptop keyboard. I resorted to sitting on the bed cross-legged with the ThinkPad
on my lap, or on the desk chair. Needless to say, it would have been more
comfortable to have an external keyboard on my lap and place the laptop on the
desk. However, since this keyboard is somewhat hefty and large, I didn't want to
travel with it (I've been lugging it back and forth to the office for the past 6
months and that's been fine though).

On OS X, the keyboard works just as you'd expect, and media keys work okay
out-of-the box.

There are some dip switches but I didn't toggle any of them. On OS X I use
[[https://pqrs.org/osx/karabiner/][Karabiner]] to flip the function and media keys, as well as to make Control
function as Escape when pressed by itself (since I changed Caps Lock to Control
in the System Preferences).
